export { createApp } from './createApp'
export { h } from './h'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './component'
export { renderSlots } from '../helpers/renderSlots'
export { provide, inject } from './apiInject'
